version: '3.3'

volumes:
  db:
    driver: local
  redis:
    driver: local
  nextcloud:
    driver: local

services:

  db:
    restart: always
    image: mariadb
    container_name: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    networks:
      - internal
    environment:
      - MYSQL_ROOT_PASSWORD='your_passwd'
      - MYSQL_PASSWORD='your_passwd'
      - MYSQL_DATABASE='your_user_db'
      - MYSQL_USER='your_user'
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - /patch/to/data/nextcloud/db:/var/lib/mysql
    labels:
      - traefik.enable=false

  redis:
    image: redis:latest
    restart: always
    container_name: redis
    command: redis-server --requirepass 'your_passwd'
    networks:
      - internal
    volumes:
      - /patch/to/data/nextcloud/redis:/var/lib/redis
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=false"

  nextcloud:
    image: nextcloud
    restart: always
    container_name: nextcloud
    networks:
      - internal
      - nextcloud
    depends_on:
      - redis
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.nextcloud.headers.browserXSSFilter=true"
      - "traefik.http.middlewares.nextcloud.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.nextcloud.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.nextcloud.headers.stsPreload=true"
      - "traefik.http.middlewares.nextcloud.headers.stsSeconds=155520011"
      - "traefik.http.middlewares.nextcloud_redirect.redirectregex.permanent=true"
      - "traefik.http.middlewares.nextcloud_redirect.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nextcloud_redirect.redirectregex.replacement=https://$${1}/remote.php/dav/"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud,nextcloud_redirect,nextcloud-https"
      - "traefik.http.routers.nextcloud.rule=Host(`${NEXTCLOUD_HOSTNAME}`)"
      - "traefik.http.routers.nextcloud.tls.certresolver=selfhostedservices"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.nextcloud.headers.customRequestHeaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.nextcloud-https.redirectscheme.scheme=https"
      - "traefik.http.routers.nextcloud-http.entrypoints=web"
      - "traefik.http.routers.nextcloud-http.rule=Host(`${NEXTCLOUD_HOSTNAME}`)"
      - "traefik.http.routers.nextcloud-http.middlewares=nextcloud-https@docker"
    environment:
      - NEXTCLOUD_ADMIN_USER='your_user'
      - NEXTCLOUD_ADMIN_PASSWORD='your_passwd'
      - MYSQL_PASSWORD='your_passwd'
      - MYSQL_DATABASE='your_user_db'
      - MYSQL_USER='your_user'
      - MYSQL_HOST=db:3306
      - TZ=Europe/Madrid
      - OVERWRITEPROTOCOL=https
      - OVERWRITEHOST=${NEXTCLOUD_HOSTNAME}
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD='your_passwd'
      - NEXTCLOUD_TRUSTED_DOMAINS='your_domain'
      - TRUSTED_PROXIES=172.19.0.0/16
    volumes:
      - /patch/to/data/nextcloud/nextcloud:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini

networks:
  nextcloud:
    external: true
  internal:
    external: false
