version: '3'

services:
  db:
    image: mariadb:focal
    env_file:
      - .env
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - internal

  redis:
    image: redis:alpine
    restart: always
    networks:
      - internal

  app:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - ./nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db:3306
      - REDIS_HOST=redis
      - TZ=Europe/Madrid
      - TRUSTED_PROXIES=172.19.0.0/16
    depends_on:
      - db
      - redis
    networks:
      - internal
    env_file:
      - .env

  web:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nextcloud:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx/
    depends_on:
      - app
    networks:
      - internal
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.services.nextcloud.loadbalancer.server.port=80
      - traefik.http.routers.nextcloud.entrypoints=web
      - traefik.http.routers.nextcloud.rule=Host(`${FQDN}`)
      - traefik.http.middlewares.nextcloud-https-redirect.redirectscheme.scheme=websecure
      - traefik.http.routers.nextcloud.middlewares=nextcloud-https-redirect
      - traefik.http.routers.nextcloud-secure.entrypoints=websecure
      - traefik.http.routers.nextcloud-secure.rule=Host(`${FQDN}`)
      - traefik.http.routers.nextcloud-secure.tls=true
      - traefik.http.routers.nextcloud-secure.tls.certresolver=letsencrypt

networks:
  internal:
  proxy:
    external: true
