version: '3'

services:
  db:
    image: mariadb:jammy
    command:
      - "--transaction-isolation=READ-COMMITTED"
      - "--binlog-format=ROW"
      - "--default-storage-engine=innodb"
      - "--character-set-server=utf8mb4"
    env_file:
      - nx.env
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql

  redis:
    image: redis:latest
    restart: always

  app:
    image: juanico/nextcloud:dev
    restart: always
    volumes:
      - ./nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db:3306
      - REDIS_HOST=redis
      - TRUSTED_PROXIES=IP_RED_DOCKER
      - TZ=Europe/Madrid
    depends_on:
      - db
      - redis
    env_file:
      - nx.env

  web:
    image: juanico/nginx-puma:cloud
    restart: always
    volumes:
      - ./nextcloud:/var/www/html:ro
    depends_on:
      - app
    ports:
      - 443:443